### ISSUE TITLE
rollup "No such file or directory"

### ISSUE THREAD

**Issue by f-saez** [arctic-hen7/perseus-starter-app#1]
Hi, 

I've read your book and decided to try your code, but I've ended-up with this error :
```
Couldn't execute command 'rollup main.js --format iife --file dist/pkg/bundle.js'. Error was: 'No such file or directory (os error 2)'
```

Here is what I've done :
```
cargo install wasm-pack
npm i -g rollup
export PERSEUS_ROLLUP_PATH=$HOME/.npm-global/bin/rollup
git clone https://github.com/arctic-hen7/perseus-starter-app.git
cd perseus-starter-app.git
perseus serve
```

I guess I've missed something but I cannot see what.

**Comment by arctic-hen7** [comment]
Hmm. I can't replicate that on my system. What OS are you using?

**Comment by arctic-hen7** [comment]
Could you try specifying `PERSEUS_ROLLUP_PATH` directly next to `perseus serve`?

I've had another report of being unable to detect `rollup` on Windows, which I assume is to do with path issues. I'm working on a fix at the moment for some Windows-specific issues, and I'll also include a change to executing these commands in shells rather than directly, which might fix these issues, particularly with `rollup`, which is installed through NPM or Yarn (and thus in a non-standard binary location, which may only be exported in certain shells).

**Comment by f-saez** [comment]
my bad, I've forgotten the obvious :-)
OS : Fedora 34 / Kernel 5.14.2  / 64 bits
Rust : rustc 1.57.0-nightly (97032a6df 2021-09-08)
shell : zsh
rollup v2.56.3
Node.js v14.17.0

```
PERSEUS_ROLLUP_PATH=$HOME/.npm-global/bin/rollup perseus serve => same error
```

.perseus directory exists and is full of files (2284 to be precise)
.perseus/main.js is present
.perseus/dist/pkg/perseus_cli_builder.js is present
.perseus/dist/pkg/bundle.js is missing.
.perseus/bundle.wasm is missing.

the trouble seem to be related to the creation of bundle.js

**Comment by arctic-hen7** [comment]
Haha no problem! My fault for not copying over some issue templates.

When you run `perseus serve`, which step of the process does it get up to successfully? I would think `Finalizing bundle...` is where it fails?

**Comment by arctic-hen7** [comment]
Oh my god I'm an idiot. The Perseus CLI doesn't accept your environment variable specification of `rollup`'s location anywhere other than in the environment checking stage! I'm pushing v0.1.4 as a fix to this right now.

**Comment by arctic-hen7** [comment]
Okay, v0.1.4 has been published, which *should* fix these problems! Please let me know how it goes!

Note: I'm yanking the previous versions of the CLI due to this.

**Comment by f-saez** [comment]
bug corrected ! :-)

thanks.

 :+1:

**Comment by arctic-hen7** [comment]
Fantastic! Happy to help!
